// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://perhldwewbieiqzpfkjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcmhsZHdld2JpZWlxenBma2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTc3NzQsImV4cCI6MjA2NDQ5Mzc3NH0.jihT77fmFPA_Cw4sD9OaNvDG3NEh8wPTQmu4QBEC5bY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);